// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHu-WMcqS7znrMYh3drREMseFw7O-Pp2A',
    appId: '1:3440730765:web:07a99ac7848dd219dab8c4',
    messagingSenderId: '3440730765',
    projectId: 'kindahclothing',
    authDomain: 'kindahclothing.firebaseapp.com',
    storageBucket: 'kindahclothing.appspot.com',
    measurementId: 'G-EYKR8RQCZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqHJP-_ePP6TwMV2mjxgQHNiXUNxxnolQ',
    appId: '1:3440730765:android:270545c63adbcaa3dab8c4',
    messagingSenderId: '3440730765',
    projectId: 'kindahclothing',
    storageBucket: 'kindahclothing.appspot.com',
  );
}
